name: Test

on:
  push:
    branches:
      - master

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependences
        run: yarn
      - name: Executing Lint
        run: yarn lint
      - name: Executing Test
        run: yarn test
